### ISSUE TITLE
Add paragraphs example

### ISSUE THREAD

**Issue by amazingrando** [fourkitchens/emulsify#10]
- Add an example of connecting Pattern Lab templates with Paragraphs.
- Add an example of connecting Pattern Lab templates with a Paragraph inside of a Paragraph. _Inception!_

**Comment by evanmwillhite** [comment]
The community is discussing moving this type of thing into a separate project, one that is purpose built for training and learning (possibly https://github.com/phase2/drupal-lab or something like it). I would like to support that effort so I'm closing out this story.
