### ISSUE TITLE
Gulp Deploy error

### ISSUE THREAD

**Issue by adamfchs** [fourkitchens/emulsify#102]
Hello,

I'm trying to move pattern lab to a pantheon dev sites for the first time.  Everything is running great locally, but when I run 'gulp deploy' I get this error:

'deploy' errored after 4.89 s
[15:53:55] Error in plugin 'gulp-gh-pages'
Message:
    Command failed: git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> gh-pages

Details:
    killed: false
    code: 1
    signal: null
    cmd: git pull

Is there something that I need to in to do in my local gulp config file to beat this?

**Comment by amazingrando** [comment]
Summoning @evanmwillhite to bring this to his attention.

**Comment by evanmwillhite** [comment]
Gulp deploy is a task for deploying the pattern lab instance as a _github_ page - it uses https://www.npmjs.com/package/gulp-gh-pages (with some specifics for Pattern Lab). So, this method won't work for deploying to Pantheon or other servers.

**Comment by amazingrando** [comment]
@evanmwillhite Should we consider renaming the task? Perhaps `gulp ghpages-deploy`?

**Comment by adamfchs** [comment]
Thanks for the quick response!

Do you know of any method of accessing the pattern-lab/public folder from a pantheon dev?

We're working on a custom upsteam/repo/cli setup with pantheon that I'm assuming would allow the gulp deploy to work from the upstream git repo, but we're not quite there yet.

**Comment by evanmwillhite** [comment]
@amazingrando good idea to rename for clarification.

@adamfchs The directories you would need are `/pattern-lab/public` and `/dist`. You could try just not gitignoring those or write a task to copy those to a single directory (which is basically what the [gh-pages branch](https://github.com/fourkitchens/emulsify/tree/gh-pages) is on github).

**Comment by adamfchs** [comment]
Great!  I'll give that a shot for now.  Thanks

**Comment by adamfchs** [comment]
Just a heads up for people with this issue in the future—
changing the gitignore file in the themes/pattern-lab folder to allow files inside /public works like a charm.

The path to view would be http://mysitename.pantheonsite.io/themes/emulsify/pattern-lab/public/

**Comment by evanmwillhite** [comment]
Awesome, thank you!
