### ISSUE TITLE
Add Views example

### ISSUE THREAD

**Issue by amazingrando** [fourkitchens/emulsify#11]
- Show an example of how to connect a Pattern Lab template with a View template.

**Comment by evanmwillhite** [comment]
Also, actual files that can be enabled as an example

**Comment by evanmwillhite** [comment]
The community is discussing moving this type of thing into a separate project, one that is purpose built for training and learning (possibly https://github.com/phase2/drupal-lab or something like it). I would like to support that effort so I'm closing out this story.
