### ISSUE TITLE
Point Pattern Lab dependencies to new Drupal Pattern Lab forks

### ISSUE THREAD

**Issue by evanmwillhite** [fourkitchens/emulsify#120]
We've made concerted efforts as a Drupal/PL community to commit to certain repos as canonical for all the Drupal/PL projects. Emulsify should leverage these. 

See https://github.com/phase2/pattern-lab-starter/pull/98/files for an example.

**Comment by ModulesUnraveled** [comment]
I agree. I'm a little out of the loop as to what those repos give us, but it's easy to switch to them if we need to.
