### ISSUE TITLE
List Emulsify on styleguides.io

### ISSUE THREAD

**Issue by astanush** [fourkitchens/emulsify#132]
Let's list Emulsify in the tools section: http://styleguides.io/tools

Here's how to add it:
https://github.com/maban/styleguides/blob/gh-pages/_resourcetool/README.md

We'll also need a 800x400 image to put in the screenshots folder:
https://github.com/maban/styleguides/tree/gh-pages/images/screenshots

**Comment by astanush** [comment]
@amazingrando This is what made me think about having an Illustrator or EPS version of the logo, but I'd like to have one on hand for general purposes too (Marketing team will more likely have Illustrator than Sketch). Thanks!

**Comment by amazingrando** [comment]
@astanush I've made an illustrator version of the logo with the pattern and without the pattern, and this is now the canonical logo. I've also cleaned up the Emulsify project folder on Dropbox.

**Comment by amazingrando** [comment]
@astanush I have this ready for you to review at https://github.com/fourkitchens/styleguides/commit/6d83a4bbfd33e9acda97740f36fec5e97c29f5ba.

Once we get the final copy approved, I'll initiate a PR to get it added.

**Comment by amazingrando** [comment]
@astanush I've figured out how to add an image and updated our repo. https://github.com/maban/styleguides/compare/gh-pages...fourkitchens:gh-pages

**Comment by astanush** [comment]
This looks great! Let's submit the PR.

**Comment by amazingrando** [comment]
@astanush PR added https://github.com/maban/styleguides/pull/367

**Comment by amazingrando** [comment]
Marked this as In Review as a reminder to check in on the PR later.

**Comment by amazingrando** [comment]
@astanush This has been merged by Brad Frost. http://styleguides.io/tools
