### ISSUE TITLE
Document workflow for d.o credit

### ISSUE THREAD

**Issue by evanmwillhite** [fourkitchens/emulsify#133]
Maybe add an issue on d.o saying all issues are taken care of on github and crediting using their syntax:

Example: (can we add a organization flag)?
```git commit -m 'Issue #2899230 by deepak_zyxware: Twig_Error_Loader: Template "@atoms/05-forms/checkbox/_checkboxes.twig" is not defined' --author="deepak_zyxware <deepak_zyxware@3127425.no-reply.drupal.org>"```

**Comment by evanmwillhite** [comment]
@ccjjmartin we researched this and found it couldn't be done without manually tagging individual commits, correct? (since we use github)

**Comment by ccjjmartin** [comment]
@evanmwillhite I researched this and found that not even tagging commits would work.  It has to have an issue on D.O (issue number) and someone has to manually use issue queue.  I am going to close this since the overhead isn't worth the benefit.
