### ISSUE TITLE
CircleCI testing for drush script

### ISSUE THREAD

**Issue by evanmwillhite** [fourkitchens/emulsify#135]

**Comment by ccjjmartin** [comment]
@evanmwillhite Maybe this should read "Add CircleCI testing" without a reference to the script specifically.  It appears we don't have any testing for PRs right now.

**Comment by evanmwillhite** [comment]
OK, sounds good. Can you do that? You would know better how to write out the details as to why we need it.

**Comment by ccjjmartin** [comment]
I am looking into this and will create a new branch for testing
