### ISSUE TITLE
Sister module for Emulsify

### ISSUE THREAD

**Issue by evanmwillhite** [fourkitchens/emulsify#137]
Catch-all for any functionality not handled well in a theme

**Comment by evanmwillhite** [comment]
What was the reason for this again @ccjjmartin? In general, I am against this, but there might have been a good reason why we added it as an issue. If there is, feel free to reopen.

**Comment by ccjjmartin** [comment]
@evanmwillhite If we wanted to support Drush 9 this was going to be necessary but we went for php script (immediately) to be followed up with a better long term solution (node script or yeoman scaffolding).
