### ISSUE TITLE
Error: ENOENT no such file 00-b ase/global/01-colors/_colors-vars.scss

### ISSUE THREAD

**Issue by adamfchs** [fourkitchens/emulsify#142]
I've been successfully running a custom cloned version of emulsify on several D8 sites and its been awesome.

Recently however, I switched over to using the theme through a custom install profile (although none of the theme files have changed). 

After running npm install and then npm start I now get a strange error:
Error: ENOENT: no such file or directory, open './/components/_patterns/00-base/global/01-colors/_color-vars.scss'

The thing that is strange about the error is not that its not finding that file, its that its even looking for it.  I deleted that file and went with a _base_color and _client_color setup.  I changed my local.gulg-config.js to reflect that change in the scssToJson section and it is working on all earlier sites.

I am running the latest versions of node.js and npm.

Was wondering if something had changed in the Emulsify-Gulp repo being called from package.json that might cause my changes in the local.gulp-config to be ignored and overridden?  I also noticed a new package-lock.json file that is created when I run npm install that was never there before.

Any ideas you have would be great. Thanks!

**Comment by ccjjmartin** [comment]
My current understanding is that this is one of the required files of Emulsify.  Can you provide a link to Pattern Lab documentation that shows this file can be replaced with (_base_color and _client_color setup)?

**Comment by adamfchs** [comment]
I had no documentation to follow on that one. I just tried it and it worked.  

You can see it in action here: http://dev-oc-pattern-base.pantheonsite.io/themes/oc_patterns/pattern-lab/public/

Here's the lines in local gulp-config:
scssToJson: [
        {
          src: themeDir + '/components/_patterns/00-base/global/01-colors/_base-color-vars.scss',
          dest: themeDir + '/components/_patterns/00-base/global/01-colors/base-colors.json',
          lineStartsWith: '$',
          allowVarValues: false
        },
        {
          src: themeDir + '/components/_patterns/00-base/global/01-colors/_client-color-vars.scss',
          dest: themeDir + '/components/_patterns/00-base/global/01-colors/client-colors.json',
          lineStartsWith: '$',
          allowVarValues: false
        },
        {
          src: themeDir + '/components/_patterns/00-base/global/02-fonts/_font-vars.scss',
          dest: themeDir + '/components/_patterns/00-base/global/02-fonts/fonts.json',
          lineStartsWith: '$',
          allowVarValues: false
        }
      ]

**Comment by ModulesUnraveled** [comment]
@adamfchs Hey! So, a lot of things have updated recently. Here's a copy of what I'm using on a project at the moment in my `local.gulp-config.js` that shows how I changed the src/dest directories like you are doing.:
```
    patternLab: {
      enabled: true,
      configFile: `${themeDir}pattern-lab/config/config.yml`,
      watchedExtensions: (['twig', 'json', 'yaml', 'yml', 'md', 'jpg', 'jpeg', 'png']),
      scssToYAML: [
        {
          src: `${themeDir}/components/_patterns/00-base/global/colors/_color-vars.scss`,
          dest: `${themeDir}/components/_patterns/00-base/global/colors/colors.yml`,
          lineStartsWith: '$',
          allowVarValues: false,
        },
      ],
    },
```

Note though, that we've updated emulsify-gulp to use scssToYAML as opposed to json. It's a lot more friendly, and allows the browser sync to actually show new/updated colors on the fly, instead of having to reload the page/restart Pattern Lab.

As to your second error `BrowserslistError: Unknown browser query - IE >= 9`
We actually realized that the thing that was checking supported browsers was completely broken, and wasn't even reading our specs there... When we fixed it, we realized we were using an incorrect syntax to specify browsers.

Here's what my working section looks like (note specifically the `autoPrefixerBrowsers` part:
```
    cssConfig: {
      enabled: true,
      src: `${themeDir}/components/_patterns/**/*.scss`,
      dest: `${themeDir}/dist/`,
      flattenDestOutput: true,
      lint: {
        enabled: false,
        failOnError: true,
      },
      sourceComments: false,
      sourceMapEmbed: false,
      outputStyle: 'expanded',
      autoPrefixerBrowsers: [
        'last 2 versions',
        'IE >= 9',
      ],
      includePaths: (['./node_modules']),
    },
```

Hopefully that helps!

**Comment by adamfchs** [comment]
@ModulesUnraveled 

The browser prefixing solution worked perfectly!! Thank you so much.

I ended up going back to the single _colors.scss to make things easier.

One last question:
Now that the npm start is running, I noticed a new thing. I get these little sass helpers (see below) that I don't really want cluttering up my terminal screen.

Is that a new emulsify function I can get rid through my local gulp-config or is that coming from npm?
250:3   ✖  Expected empty   rule-empty-line-before
            line before
            rule
 250:21  ✖  Expected single  block-opening-brace-space-before
            space before
            "{"
 251:4   ✖  Expected         indentation
            indentation of
            6 spaces
 252:4   ✖  Expected empty   at-rule-empty-line-before
            line before

**Comment by ModulesUnraveled** [comment]
That's the sass linting. You should have a .stylelintrc (I think that's the name) in your theme root. By default we're using airbnb's coding standards (maybe with some modifications) you should be able to update that to fit your preferred coding style, or just fix the issues it's pointing out to follow broader coding standards.

**Comment by adamfchs** [comment]
Was just researching and found that out. Thanks for the quick response though.  I like the theory of it, but need to rewrite or scrap some of the rules.

And/or do it the way everyone else is doing it.

Thanks again for all the help.

**Comment by ModulesUnraveled** [comment]
No problemo!
