### ISSUE TITLE
Custom fonts integration

### ISSUE THREAD

**Issue by sinyayadynya** [fourkitchens/emulsify#143]
Hi,

Is there a better way than @fontyourface Drupal module to integrate custom fonts?

I'm not sure if it is possible to follow the way of custom icons (`/web/themes/custom/corp/components/fonts/icons...`)

Have tried to add some fonts to `/web/themes/custom/corp/components/fonts` together with a 
`/web/themes/custom/corp/components/css/scss/objects/_myfont.scss` file to see if anything happened, without chance.

Anything that I am missing?

**Comment by evanmwillhite** [comment]
You can use custom fonts however you like in this theme - however, the directories you mention have some caveats.

`/web/themes/custom/corp/components/fonts` is the default fonts directory shipped with Pattern Lab (not Emulsify-specific). You can put fonts into that directory, but I would recommend putting them into the `/web/themes/custom/corp/fonts/` directory instead (as it is not mixed in with Pattern Lab's). Likewise, `/web/themes/custom/corp/components/css/` is the directory for the default shipped with Pattern Lab (again, not Emulsify-specific). Running `npm start` only compiles scss in the `/web/themes/custom/corp/components/_patterns/` directory, so you will not want to put your styles into that directory.

**Comment by StevenDesignCo** [comment]
What is the best practice for fonts hosted elsewhere? Like typography.com. For both the theme and Pattern Lab.
