### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by micheljp** [fourkitchens/emulsify#145]
I've installed the repo via composer and created a subtheme via drush emulsify "theme name".  I've enabled the theme and am able to create twig templates and accompanying sass files.  Running npm start successfully compiles everything for drupal as a theme.  But I don't know how the patternlab styleguide is generated or where it lives?

**Comment by ModulesUnraveled** [comment]
The PatternLab styleguide is generated when you run `npm start` (and updated live each time you save a change to a file) and at the bottom of the initial output you should see something like:
```
...
... bunch of output ...
...
[Browsersync] Access URLs:
 ----------------------------------------------------
    Local: http://localhost:3000/pattern-lab/public/
 External: http://10.0.1.1:3000/pattern-lab/public/
```

You can access the pattern lab instance at either one of the urls you see there. (Your actual URLs may vary)

**Comment by micheljp** [comment]
hmm... i'm running this from inside a vagrant box. those urls aren't working for me..

**Comment by micheljp** [comment]
okay i figured it out.  swapped out localhost with IP vagrant was running.

**Comment by micheljp** [comment]
thank you.

**Comment by ModulesUnraveled** [comment]
Sweet!
