### ISSUE TITLE
Switch back to PL core instead of DPL fork

### ISSUE THREAD

**Issue by evanmwillhite** [fourkitchens/emulsify#155]
Now that things are rolling on Pattern Lab core side again, we can switch back to it from the Drupal Pattern Lab fork ([merged into core](https://github.com/pattern-lab/patternlab-php-core/releases/tag/v2.8.0)).

**Comment by EvanLovely** [comment]
Yep, things are good to go! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
