### ISSUE TITLE
Twig components compiling in patternlab but not in Drupal front-end

### ISSUE THREAD

**Issue by LordRembo** [fourkitchens/emulsify#160]
I'm fairly new to the component-based Drupal approach, so apologies if I'm missing something.
I followed the instructions to install Emulsify (v2.2) on a new D8 installation (8.3.1) last Friday, and got it running in a clone of the Emulsify theme.
However, while I can see my changes to twig-components on the patternlab url (eg. for a menu-item), I can't get the Drupal site front-end to display any changes.
It does render changes made in twig-files from the original 'templates'-folder though (Twig is in debug mode, cache is turned off). 
I don't know if this means the Components module (v1.0) is not doing its job or if it's related to the npm/gulp tasks (no errors, seem to be running and updating).
Any insights would be greatly appreciated.

**Comment by LordRembo** [comment]
I finally got it working, when I 1) set installed & set a non-emulsify theme as default, 2) uninstalled the original 'Emulsify' theme and 3) set the cloned 'Emulsify' theme as default again.
No idea why but maybe it'll help someone else figure things out.

**Comment by evanmwillhite** [comment]
Thanks for letting us know about this. I think I may have run into this myself too if I'm understanding you right (having to disable the Emulsify theme when you have another original custom clone). Either way, I've added that to the README and wiki. Let me know if you think I should tweak anything in terms of instructions beyond that. Thanks!

**Comment by LordRembo** [comment]
Hi Evan, 
I do think it would be handy to include some possible trouble-shooting info about this, in the Wiki.
Otherwise, great project!
