### ISSUE TITLE
Using Drupal twig functions

### ISSUE THREAD

**Issue by leonk** [fourkitchens/emulsify#169]
I'm just testing out emulsify, have got everything up and running, and started to build out some components with it.

However, when I used a drupal specific twig function (e.g. `file_url()`) I get errors compiling in patternlab, e.g.
```
Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'Unknown "file_url" function in "{#
```

Also when using drupal twig extensions, such as https://www.drupal.org/project/twig_field_value

Is there a way to import these functions so that they can be used within patternlab?

**Comment by evanmwillhite** [comment]
The quick answer is there is definitely a way to make Twig extensions (functions, filters, etc.)  not _break_ Pattern Lab. [`/components/twig-components`](https://github.com/fourkitchens/emulsify/tree/develop/components/_twig-components) is where Pattern Lab expects to find custom Twig extensions. 

If not breaking PL is enough, you'll notice a lot of those defaults ones are just returning the string that's entered (not doing anything, but also allowing Pattern Lab to move on without errors). If you _do_ need the actual functionality on the Pattern Lab side, you can start by copying or symlinking those Twig extensions into those respective folders above and just seeing if they work. 

**A word of caution though** - make sure any extensions that already exist in Drupal follow the "pl_" naming convention of the others, as that is what tells the module we use to share plugins between Pattern Lab and Drupal (Unified Twig Extensions) to _not_ add those to Drupal (which ends up overriding Drupal's).

**Comment by amazingrando** [comment]
Closing as resolved. (If not, comment and I'll reopen.)
