### ISSUE TITLE
BEM function returns an error if no context attributes

### ISSUE THREAD

**Issue by LordRembo** [fourkitchens/emulsify#172]
Not sure if this is an Emulsify thing or part of Drupal Patternlab, so apologies if I'm in the wrong place. The BEM function is missing a few checks I think.
There's a `foreach` loop around line 43 that loops any attributes in search of classes to add. In some cases (as I just found out while adding multiple file fields), there's not always attributes to loop through. So basically, before starting every loop, there should be a check to see if the element isn't null or empty.

**Comment by evanmwillhite** [comment]
I moved this [to the BEM extension repo](https://github.com/drupal-pattern-lab/bem-twig-extension/issues/8), but thanks for filing this!
