### ISSUE TITLE
Adding youtube videos about Emulsify to Wiki examples

### ISSUE THREAD

**Issue by shaal** [fourkitchens/emulsify#173]
I prepared a youtube playlist of Emulsify videos I was able to find -
https://www.youtube.com/playlist?list=PLO9S6JjNqWsGMQLDfE8Ekt0ryrGa3g4km

**Comment by evanmwillhite** [comment]
Nice! I'd like to move these into a Tutorials Wiki page that gets added to the README. I'll leave this issue open until we're able to do that. Thanks for getting the ball rolling!

**Comment by amazingrando** [comment]
I've added a link to the list of videos to [this page](https://github.com/fourkitchens/emulsify/wiki) and added it to the README in #175
