### ISSUE TITLE
Adding a view to templates directory

### ISSUE THREAD

**Issue by shaal** [fourkitchens/emulsify#177]
Can you please add a view to the template directory and connect it with the cards-grid component?

**Comment by amazingrando** [comment]
@shaal Good idea. I've labeled this as a feature request.

**Comment by sinyayadynya** [comment]
That's would be great, because I can't get through this too.

**Comment by ModulesUnraveled** [comment]
This was done in https://github.com/fourkitchens/emulsify/pull/238
