### ISSUE TITLE
Can't set background image in .scss files

### ISSUE THREAD

**Issue by crashspringfield** [fourkitchens/emulsify#193]
I'm trying to set a background image in a .scss file but it doesn't work.

test.twig:

    <div class="test"></div>

_test.scss

    .test {
        background-image: url(../../images/ic_label_outline_black.png);
        background-size: cover;
        width: 20px;
        height: 16px;
        display: inline-block;
    }

However, when I use inline styling it works fine:

    <div style="background-image: url(../../images/ic_label_outline_black.png);
                       background-size: cover;
                       width: 20px;
                       height: 16px;
                       display: inline-block;"></div>

**Comment by evanmwillhite** [comment]
All the scss is compiled into a single dist/style.css file so your image path in the css has to be relative to that file. I believe it's `../components/images/` for the directory you're referring to.

**Comment by crashspringfield** [comment]
That seems to work both on the Drupal and Pattern Lab side of things. Thanks!
