### ISSUE TITLE
Twig_Error_Syntax: Unknown "bem" function

### ISSUE THREAD

**Issue by sinyayadynya** [fourkitchens/emulsify#194]
Hi,

I'm getting this error while enabling Emulsify on a new project (Drupal 8.5.x-alpha1):

`Twig_Error_Syntax: Unknown "bem" function. in Twig_ExpressionParser->getFunctionNodeClass() (line 13 of ../web/themes/contrib/emulsify/components/_patterns/01-atoms/03-lists/00-ul.twig).`

Never encountered it on other project, maybe because D 8.5 ? The beta version should be released soon. I will try again at that point and let you know. But if you have any suggestion in between, this is most welcome.

**Comment by evanmwillhite** [comment]
What installation steps did you take when enabling Emulsify?

**Comment by sinyayadynya** [comment]
I had to take mixed steps. Starting with composer (composer require fourkitchens/emulsify) but then, when drushing 
`drush en emulsify components unified_twig_ext -y`
i got
`[error]  Unable to install modules emulsify, components, unified_twig_ext due to missing modules emulsify.`
Therefor I enabled manually the modules and the theme via Drupal interface.

**Comment by evanmwillhite** [comment]
I think you may just need to run `yarn install` or `npm install` now. The [BEM](https://github.com/drupal-pattern-lab/bem-twig-extension) and [Add Attributes](https://github.com/drupal-pattern-lab/add-attributes-twig-extension) Twig extensions are added in that postinstall script.

**Comment by sinyayadynya** [comment]
Yes that made it! Forgot that it was necessary to run it before 'watching' the theme.
