### ISSUE TITLE
Setting the 'Hamburger menu' as optional (disabled by default)

### ISSUE THREAD

**Issue by sinyayadynya** [fourkitchens/emulsify#196]
What about setting the 'Hamburger menu' as optional (disabled by default)?

Many UI/UX studies suggest that this is far from a best practice, as most people do not click on the hamburger icon.

My idea is that it is a nice option to have but should not be enabled by default. What do you think about it?

**Comment by ModulesUnraveled** [comment]
Every example pattern included with Emulsify is just that, an example. Emulsify should not be used as an actual production theme, so if you don't want it, don't use it in your cloned custom theme. 

One reason it is included is that it shows how to include twig, css, and js in a single component, so I don't think there's any reason to remove or disable it.


I would be interested in reading the studies you mention about the hamburger not being an effective design pattern though. If you could share those, I'd be very grateful!

**Comment by sinyayadynya** [comment]
I understand and appreciate to have it as an example, only I feel not super comfortable to remove it on all my project. Of course, if I'm the only one to avoid hamburger diet, then it is perfectly ok to leave it as it is.

However, I'm glad to share some reading about the hamburger menu damaging UX and some alternatives:

- http://whatusersdo.com/blog/hamburger-menus-damage-ux/?ref=webdesignernews.com
- https://www.webdesignerdepot.com/2018/02/why-the-hamburger-menu-should-disappear-for-good
- https://www.webdesignerdepot.com/2016/11/4-fresh-alternatives-to-the-hamburger-menu
- https://uxplanet.org/great-alternatives-to-hamburger-menus-d4c76d9414dd

PS: maybe I'm also not using the best way to remove the default navigation system in Emulsify. If you have any tip about it, it will be welcome. Thanks!

**Comment by evanmwillhite** [comment]
> The hamburger diet 😆 

@ModulesUnraveled is right about Emulsify's default components being merely examples of what can be done. But, there are a few Emulsify components that are connected by default with their respective Drupal templates and menu is one of them. The file that ties the Drupal menu to the Emulsify one is [/templates/navigation/menu--main.html.twig](https://github.com/fourkitchens/emulsify/blob/develop/templates/navigation/menu--main.html.twig). If you want to use Drupal's default, you can either delete that file from your Emulsify theme or even just change it back to Emulsify's parent theme Stable's menu.html.twig markup (see below).

Or you can of course just edit Emulsify's menu component and do whatever you like with it including remove the icon, change styling, etc. That's why we call Emulsify a starterkit rather than a base theme. The goal is definitely to edit or remove any component as you like to suit your needs.

Hope this helps!

```
{#
/**
 * @file
 * Theme override to display a menu.
 *
 * Available variables:
 * - menu_name: The machine name of the menu.
 * - items: A nested list of menu items. Each menu item contains:
 *   - attributes: HTML attributes for the menu item.
 *   - below: The menu item child items.
 *   - title: The menu link title.
 *   - url: The menu link url, instance of \Drupal\Core\Url
 *   - localized_options: Menu link localized options.
 *   - is_expanded: TRUE if the link has visible children within the current
 *     menu tree.
 *   - is_collapsed: TRUE if the link has children within the current menu tree
 *     that are not currently visible.
 *   - in_active_trail: TRUE if the link is in the active trail.
 */
#}
{% import _self as menus %}

{#
  We call a macro which calls itself to render the full tree.
  @see http://twig.sensiolabs.org/doc/tags/macro.html
#}
{{ menus.menu_links(items, attributes, 0) }}

{% macro menu_links(items, attributes, menu_level) %}
  {% import _self as menus %}
  {% if items %}
    {% if menu_level == 0 %}
      <ul{{ attributes }}>
    {% else %}
      <ul>
    {% endif %}
    {% for item in items %}
      <li{{ item.attributes }}>
        {{ link(item.title, item.url) }}
        {% if item.below %}
          {{ menus.menu_links(item.below, attributes, menu_level + 1) }}
        {% endif %}
      </li>
    {% endfor %}
    </ul>
  {% endif %}
{% endmacro %}
```

**Comment by amazingrando** [comment]
This issue looks resolved so I'm closing it. If it isn't, feel free to reopen it!

**Comment by sinyayadynya** [comment]
@evanmwillhite thanks for your reply. By the time, I finding more and more comfortable with the basic use of Emulsify, and I'm grateful for all your answers.

Actually, I'm using the second approach that you are suggesting, modifying the Emulsify's menu component. 

However, and not only because I'm lazy, but also because I'm everytime worried to forget something, among the bunch of modifications, including:

- removing the 'main_menu' library from emulsify.libraries.yml
and inside 02-molecules/menus/main-menu:
- deleting main-menu.js 
- deleting _03-main-menu-toggle.scss
- cleaning main-menu.twig
- cleaning _00-main-menu.scss

(please tell me if the list in incomplete)

Ideally, but I don't know how to implement that, it would be great to have an option in emulsify.php (a bit like the '--slim' one) allowing to create the custom theme without the burger menu. 

Of course, I can live without it, and this is just a suggestion.
