### ISSUE TITLE
Failed to extract the starterkit

### ISSUE THREAD

**Issue by igorlakic** [fourkitchens/emulsify#209]
`failed to extract the starterkit. easiest solution is to manually download it and copy <path>./dist</path to ./source/`

This error appeared yesterday when I tried to install Emulsify on the dev environment with PHP 7.2. There are no similar issues with PHP 7.1. 
I guess that something similar also happened in [#147](https://github.com/fourkitchens/emulsify/issues/147), but with some other PHP version (maybe with 7.1.9 or something like that)...

**Comment by evanmwillhite** [comment]
@igorlakic Does this issue still exist or is it a duplicate of #147?

**Comment by igorlakic** [comment]
@evanmwillhite I haven't tried it again since my previous comment. It works nice with PHP 7.1...

**Comment by evanmwillhite** [comment]
OK, I'm gonna close and we can always reopen if needed. Thank you!
