### ISSUE TITLE
Including core language switcher component

### ISSUE THREAD

**Issue by sinyayadynya** [fourkitchens/emulsify#211]
Hi,

Would it be possible to give the core language block a similar treatment as menu list, with the option to display its links inline?

I have tried to create a 'links list' component, but without success yet. Any help would be welcome and why not to include it into Emulsify?

**Comment by evanmwillhite** [comment]
This could be done in a tutorial, but we try to stay away from making assumptions about what components will be needed for certain functionality in Drupal.
