### ISSUE TITLE
trans tags do not work

### ISSUE THREAD

**Issue by iStryker** [fourkitchens/emulsify#212]
If you add a trans tag to pattern lab such as 
`{% trans %} My name is {{ name }}. {% endtrans %}` in a twig file it becomes

> My name is @name 

Shouldn't it output the name it finds in the .yml file?

**Comment by sinyayadynya** [comment]
I'm also lost on that point.

**Comment by iStryker** [comment]
I just renamed the file pl_trans or whatever,  if you add pl_ in front of the file it will only be used in pattern lab.    I created a pull request #214 that should fix this.

**Comment by evanmwillhite** [comment]
Fixed with https://github.com/fourkitchens/emulsify/pull/239
