### ISSUE TITLE
emulsify command not found

### ISSUE THREAD

**Issue by mohammadpasha21** [fourkitchens/emulsify#215]
I am trying to install emulsify on composer based Drupal project.

I could run composer require fourkitchens/emulsify
2.Enable Emulsify and its dependencies drush en emulsify components unified_twig_ext -y
At step 2 I get below error:
![image](https://user-images.githubusercontent.com/18069289/37591635-302e1d6e-2b92-11e8-8fb4-c83c6ee1f116.png)

**Comment by ccjjmartin** [comment]
@mohammadpasha21 It has been a while since I have ran into this so forgive me if this is bad advice but I think you don't need to "enable" emulsify as it is a theme.  You should be able to configure the "default" theme after the other two modules you listed are enabled.

**Comment by thamas** [comment]
@mohammadpasha21  Drush 9.x has separate commands to enable themes and modules.

See: https://github.com/fourkitchens/emulsify/pull/217/files#diff-04c6e90faac2675aa89e2176d2eec7d8R28

**Comment by evanmwillhite** [comment]
Since there is work being done toward [better supporting Drush 9](https://github.com/fourkitchens/emulsify/pull/218), I am going to close this. Feel free to reopen if help is still needed beyond that.
