### ISSUE TITLE
Include .nvmrc

### ISSUE THREAD

**Issue by thamas** [fourkitchens/emulsify#216]
You recommend using nvm. I think an .nvmrc file should be included in the theme because it does not hurt those who do not use nvm but helps those who do. 

My default node version is node 9.4 and with that `yarn install` just broke. I've added an .nvmrc file which sets node 8.4 and it fixed the `yarn install` issue.

**Comment by evanmwillhite** [comment]
I wonder if this was a bug with a specific version of node. I'm on 9.7.0 and just tested `yarn install` and `yarn start` without any errors. I'm going to close for now, but if anyone else runs into this or you are still having issues @thamas, feel free to reopen.
