### ISSUE TITLE
Wiki page: Gulp Config has wrong instructions(?)

### ISSUE THREAD

**Issue by thamas** [fourkitchens/emulsify#219]
https://github.com/fourkitchens/emulsify/wiki/Gulp-Config

> 1. Create local.gulp-config.js in your root directory and copy/override contents from the original
> 2. In that file, set the theme path accordingly, e.g. var themeDir = './docroot/themes/custom/emulsify/'; 

`var themeDir` is `./` in the original file. If I change it in the local version according to the suggestion (writing "web" in my case instead of "docroot") it won't work (and throw errors about unreachable pattern lab config).

> 3. Also, set the browserSync startPath variable, e.g., startPath: 'docroot/themes/custom/emulsify/pattern-lab/public/',

The path should not include the "docroot" (or similar).

**Comment by evanmwillhite** [comment]
We're using this setup on projects here, and I just tested it by moving `local.gulp-config.js` to the root of a new Emulsify installation, so using that file appears to work fine. Are you saying that it is not working for you or just that we should change our instructions to fit something else? Just want to make sure I'm understanding you correctly.

If you are running into errors with usage, please provide either a link to your repo or as many details as possible such as your Emulsify theme name (if not emulsify), the path from the root of your project to the theme and your local config file contents. Thanks!

**Comment by thamas** [comment]
I want(ed) to suggest to change the instructions because I found that they are not OK currently. 

While I try do everything right, it is possible, that I done something in a wrong way.

It is just a bare new Composer based Drupal 8.5 install to test Emulsify from the start. It currently has no a repo but I can create one. 

Because the `drush emulsify` command did not work for me (see https://github.com/fourkitchens/emulsify/issues/182#issuecomment-374561001) I just used the original Emulsify theme in the themes/contrib folder of Drupal.

I created a local.gulp-config.js file, copying the original one (mainly to set BrowserSync for my local install), and found these instructions in the Wiki and I folowed them.

When I followed the 3. point I got an URL like this: http://localhost:3000/web/themes/contrib/emulsify/pattern-lab/public/ which results only a "Page not found" message from Drupal. (My drupal root is "web", not "docroot".)

The original `startPath: 'pattern-lab/public/'` also results just a "Page not found" for me.

Following the 2. point I set 
`var themeDir = './web/themes/contrib/emulsify/'`

And when I run `yarn start` I got a long error message starting with 

    fs.js:652
    return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode)
    Error: ENOENT: no such file or directory, open './web/themes/contrib/emulsify/pattern-lab/config/config.yml'`

I changed `${themeDir}` occurrences to `./` inside the patternLab object and the error message has gone. And when I edited a twig file my styleguide was updated.

But when I edited an scss file, nothing happened. That was the point when I set back to 
`var themeDir = './'`. I also added back `${themeDir}`s to the patternLab object and this way it works.

Last I think I should mention that I use(d) Node 8.4.

**Comment by evanmwillhite** [comment]
Thanks for all this info - it's very helpful! Where was your `local.gulp-config.js` file located when it was giving you that error?

**Comment by thamas** [comment]
You are welcome! :)
It's in the root of the template, next to eg. gulpfile.js.

**Comment by thamas** [comment]
You should know that too, that it is the latest _normal_ release of Emulsify (v2.2 – added by Composer), _not_ the latest _development_ release!

**Comment by thamas** [comment]
@evanmwillhite FYI Here is a duplicate (via https://github.com/fourkitchens/emulsify/pull/218) of the mentioned codebase: https://gitlab.com/thamas/emutant

**Comment by thamas** [comment]
Hm, just re-read the wiki page and noticed, that you wrote:

> …if you want to run all gulp tasks _from the root of a Drupal 8 project_…

So what you are talking about that it is the _root of the whole project,_ outside of the public web folder (called "web" or "docroot") if I understand right. 

But my file was in the root of the theme. My bad!

Not checked it yet, but that can be the source of the problem I think… :)

**Comment by thamas** [comment]
By the way, why would someone locate the Gulp config file in the root of the project when it is a tool for _frontend (theming)_ tasks…?

**Comment by ModulesUnraveled** [comment]
On some projects, we use gulp for things other than just frontend work. It's really just a build tool. It's not necessarily frontend specific.

We do things like defining a rebuild task that gets the database, runs `composer install`, runs `config-import`, etc. to reset the local environment for each new ticket. (or when reviewing someone else's PR)

Gulp is just the tool that we can use to string together a bunch of commands needed to complete a task, and share those commands with other developers so that we're all developing on similar environments. And so that we don't forget any of the steps along the way.

So, the _project's_ gulp file is usually in the project root. The theme tasks can be defined anywhere, typically the project root, or the theme root.

Hope that helps!

**Comment by thamas** [comment]
Thanks for your answer, Brian!

This can be closed, I think. :)
