### ISSUE TITLE
Placeimg HTTPS error in Chrome

### ISSUE THREAD

**Issue by johnny5th** [fourkitchens/emulsify#221]
It looks like https://placeimg.com uses a distrusted Symantec cert. I've switched to https://picsum.photos on my project to get rid of the https errors in PL. Since we don't know if and when they'll get a new cert, should we switch to a different placeholder image provider?

**Comment by terrabruder** [comment]
@evanmwillhite It looks like https://placeimg.com is now using an updated cert. Should this be closed?
