### ISSUE TITLE
Children menu-items receive parent item attributes

### ISSUE THREAD

**Issue by johnny5th** [fourkitchens/emulsify#222]
`item_modifiers` inside of `_menu-item.twig` are being modified for the particular menu item, then are passed down to children with the `menu.menu_links` macro.
Note, for example, the `.main-side-menu__item--active` and  `.main-side-menu__item--with-sub` classes on the menu children.

Unpatched HTML output partial:
```
<ul data-region="sidebar" class="main-side-menu">
  <li class="main-side-menu__item main-side-menu__item--active main-side-menu__item--with-sub">
    <a class="main-side-menu__link main-side-menu__link--active main-side-menu__link--with-sub" href="/academics/academic-departments/school-business">
    School of Business
    </a>
    <span class="expand-sub"></span>
    <ul class="main-side-menu main-side-menu--sub main-side-menu--sub-1">
      <li class="main-side-menu__item main-side-menu__item--active main-side-menu__item--with-sub main-side-menu__item--sub main-side-menu__item--sub-1">
        <a class="main-side-menu__link main-side-menu__link--active main-side-menu__link--with-sub main-side-menu__link--sub main-side-menu__link--sub-1" href="/academics/academic-departments/school-business/institute-economic-education">
        Institute of for Economic Education
        </a>
      </li>
```

Patched HTML output partial:
```
<ul data-region="sidebar" class="main-side-menu">
  <li class="main-side-menu__item main-side-menu__item--active main-side-menu__item--with-sub">
    <a class="main-side-menu__link main-side-menu__link--active main-side-menu__link--with-sub" href="/academics/academic-departments/school-business">
    School of Business
    </a>
    <span class="expand-sub"></span>
    <ul class="main-side-menu main-side-menu--sub main-side-menu--sub-1">
      <li class="main-side-menu__item main-side-menu__item--sub main-side-menu__item--sub-1">
        <a class="main-side-menu__link main-side-menu__link--sub main-side-menu__link--sub-1" href="/academics/academic-departments/school-business/institute-economic-education">
        Institute of for Economic Education
        </a>
      </li>
```

Possible Patch Diff:
```
diff --git a/web/themes/custom/etbu/components/_patterns/02-molecules/menus/_menu-item.twig b/web/themes/custom/etbu/components/_patterns/02-molecules/menus/_menu-item.twig
index 86f5dae..b9edefe 100644
--- a/web/themes/custom/etbu/components/_patterns/02-molecules/menus/_menu-item.twig
+++ b/web/themes/custom/etbu/components/_patterns/02-molecules/menus/_menu-item.twig
@@ -1,6 +1,8 @@
 {% if not item_modifiers %}
   {% set item_modifiers = [] %}
 {% endif %}
+{# Pass original item modifiers down to children #}
+{% set original_item_modifiers = item_modifiers %}
 {% if item.in_active_trail == TRUE %}
   {% set item_modifiers = item_modifiers|merge(['active']) %}
 {% endif %}
@@ -30,7 +32,7 @@
     } %}
     {% if item.below %}
       <span class="expand-sub"></span>
-      {{ menus.menu_links(item.below, attributes, menu_level + 1, menu_class, menu_modifiers, menu_blockname, item_base_class, item_modifiers, item_blockname) }}
+      {{ menus.menu_links(item.below, attributes, menu_level + 1, menu_class, menu_modifiers, menu_blockname, item_base_class, original_item_modifiers, item_blockname) }}
     {% endif %}
   {% endblock %}
 {% endembed %}
```

**Comment by clintrobinson** [comment]
I had what I believe is the same issue with _menu-item.twig and when I removed the if statement surrounding 
`{% set item_modifiers = [] %}`
that solved the issue for me. I am not sure of the necessity of the if statement and if my solution has long term implications, but this did fix the issue for me.

**Comment by johnny5th** [comment]
It seems like removing that if statement negates the need for the item_modifiers parameter on the menus.menu_links macro. Maybe we need some sort of flag that allows/disallows parent item_modifiers to pass down to their children?

**Comment by clintrobinson** [comment]
I am confused by what you are saying. I'm removing the if statement, but I am not removing the `{% set item_modifiers = [] %}` code. The initialized array is still there and active/sub/with-sub are still being merged in. So the item_modifiers does exist and it now seems to function properly for me. I guess I am a bit ignorant to what that if statement is even doing.

**Comment by johnny5th** [comment]
Apologies for not being clear. By removing the if statement, the item_modifiers variable is being reset each time the _menu-item.twig file is called. One of the parameters of the menus.menu_links macro allows passing item_modifiers down to _menu-item.twig.

By removing the if statement, you're successfully resetting the item_modifiers, clearing out the additional active/sub/with-sub attributes for child items. But the side effect to that is additional item_modifiers can never be passed down to the menu items.

**Comment by tparssinen** [comment]
Ran into this issue today. Fixed it by resetting the `menu_modifiers`and `item_modifiers` values from child elements (inside `{% if item.below %}`) in _menu-item.twig. I'm not sure why those variables were inherited in the first place, seems like only the root level requires them.
