### ISSUE TITLE
Can't add a new region in v. 2.3

### ISSUE THREAD

**Issue by sinyayadynya** [fourkitchens/emulsify#228]
I'm unable to add a new region (i.e. 'hero' between 'header' and 'content' in the new 2.3 version. That was previously working in 2.2.

Could you please explain what changed and how to proceed? Thanks for help.

**Comment by evanmwillhite** [comment]
There's been no changes that should affect adding regions in Drupal, so we need more info here. The files controlling the regions are still the same [info](https://github.com/fourkitchens/emulsify/blob/develop/emulsify.info.yml) file, the [page template](https://github.com/fourkitchens/emulsify/blob/develop/templates/layout/page.html.twig) and [the component](https://github.com/fourkitchens/emulsify/blob/develop/components/_patterns/05-pages/_page.twig) it references.

**Comment by sinyayadynya** [comment]
As I was using custom theme, just needed to uninstall Emulsify to solve the issue. Thanks.
