### ISSUE TITLE
"Includes: %includes" under "Available updates"

### ISSUE THREAD

**Issue by igorlakic** [fourkitchens/emulsify#233]
When I go to see "Available updates" (_admin/reports/updates_) on the Drupal site with Emulsify theme enabled and set as default (original Emulsify or its clone, the same result), I get these "_**Includes: %includes**_" things.  

Template which is being called for this "Include" element is:
_core/themes/stable/templates/admin/update-project-status.html.twig_. 
I haven't found a reason for this issue yet but it seems that something from the Emulsify theme is blocking `includes` variable.

![Imgur](https://i.imgur.com/dQjXMsF.png)

**Comment by thamas** [comment]
I did not look after it, but I have the same issue on a site using Emulsify 2.2

**Comment by evanmwillhite** [comment]
This will be fixed with [this PR](https://github.com/fourkitchens/emulsify/pull/239). We have a Twig extension in our Pattern Lab instance that isn't namespaced (trans).  It should only be used in Pattern Lab, but is incorrectly being used by Drupal currently.

**Comment by igorlakic** [comment]
...works like a charm. 👍
