### ISSUE TITLE
Remove Singularity and all the Float stuff

### ISSUE THREAD

**Issue by ModulesUnraveled** [fourkitchens/emulsify#244]
By default, we shouldn't be using floats for layout in the year 2018.

Everything we're floating right now, can be easily, and properly achieved using flexbox.

We need to update the few places we're "clear"ing stuff and remove the singularity info from `styles.scss` and `breakpoints.scss`.

Emulsify is supposed to be a "Starter Kit". I would never use Singularity on a new build, which is totally a personal preference, so anyone else is welcome to do it, but having it in there by default adds a lot of assumptions out of the box that I don't think fit **The Emulsify Way (tm)**.

e.g. Our sidebar and main content are currently being floated just because their class names happen to match something that singularity has styles defined for. I didn't ask for them to be floated, and don't want them to, but I don't have a choice if I want to keep the class names the same. And overriding default css in the only place it's used is just silly.

**Comment by evanmwillhite** [comment]
I agree wholeheartedly about getting rid of singularity. But I do have a question. The consensus around the interwebs seems to be grid for outer layout and flex for simpler smaller sections. Do we try and introduce grid for the page level layout CSS? I'm a fan of trying this, but I wanted to check with everyone else.

**Comment by ModulesUnraveled** [comment]
We used Flex on Ithaca, and everything was just fine. We weren't doing any crazy grid stuff, so I didn't take the time to learn grid.

I've heard the same thing around the web (use grid for main layout stuff), but I'm not familiar enough with it to implement it right now.

I propose I initially implement flex, so that we're at least using a modern layout tool. Then we can do a followup PR to "upgrade" to css grid at a later time

**Comment by sinyayadynya** [comment]
I also see Grid as being complementary to Flexbox (and usually more used in 'outer layout'). However, when I'm using Grid, I'm still coupling it with some Flex 'fallbacks' in order to target old browsers.

**Comment by ipwa** [comment]
"I propose I initially implement flex, so that we're at least using a modern layout tool. Then we can do a followup PR to "upgrade" to css grid at a later time"

I second this.

**Comment by evanmwillhite** [comment]
Ok, sounds great to me. Thanks!

**Comment by ModulesUnraveled** [comment]
This issue was fixed in the above PR(s)
