### ISSUE TITLE
Fieldset template removes legend_span.attributes

### ISSUE THREAD

**Issue by johnny5th** [fourkitchens/emulsify#248]
I noticed a problem when a customer used a webform element that had nested fieldsets. The legend of the element was visually duplicated. After a bit of digging, a classy-based theme indeed had the legend duplicated on the nested fieldset (I assume for accessibility) but an extra `visually-hidden` class was added to a span within the `<legend>` tag.

Replacing the emulsify legend code with the classy code resolved this issue.
```
{%
    set legend_span_classes = [
      'fieldset-legend',
      required ? 'js-form-required',
      required ? 'form-required',
    ]
  %}
  {#  Always wrap fieldset legends in a <span> for CSS positioning. #}
  <legend{{ legend.attributes }}>
    <span{{ legend_span.attributes.addClass(legend_span_classes) }}>{{ legend.title }}</span>
  </legend>
```

I didn't dig in enough to see if this comes from Drupal or if it's a webform feature, but 'visually-hidden' was added to the `legend_span.attributes` object.

Steps to repeat:
Using webform with an emulsify theme, add a `checkboxes_other` element, add a title, and view the rendered form.

**Comment by evanmwillhite** [comment]
@johnny5th I'm not able to duplicate this using your steps above. Do I need to do something else?

![screen shot 2018-08-08 at 1 17 31 pm](https://user-images.githubusercontent.com/18293479/43856185-719ed1a4-9b0d-11e8-99ba-8de66134e9fe.png)

**Comment by evanmwillhite** [comment]
Closed due to inactivity.
