### ISSUE TITLE
What is the recommended way to add additional custom gulp tasks? 

### ISSUE THREAD

**Issue by miller2676** [fourkitchens/emulsify#249]
I'm building an theme based off of Emulsify (cloned via drush as recommended) and I was wondering what the recommended best practice was for creating additional custom gulp tasks?

**Comment by evanmwillhite** [comment]
If they are wholly separate from the [Emulsify Gulp](https://github.com/fourkitchens/emulsify-gulp) tasks, then you should be able to just put them into `gulpfile.js`. If you need to integrate them into Emulsify Gulp tasks, I'm guessing you would want to fork that repo and run your own version of that by specifying it in [package.json](https://github.com/fourkitchens/emulsify/blob/develop/package.json#L6).

**Comment by miller2676** [comment]
Thanks @evanmwillhite. 
I only have few simple ones, so far, that i've included in gulpfile.js. So thanks for the confirmation. 
But forking is a good idea if/when I ever need to integrate with Emulsify Gulp.
