### ISSUE TITLE
Warning message when running `npm install` for the first time

### ISSUE THREAD

**Issue by shaal** [fourkitchens/emulsify#257]
When running `npm install` for the first time, I receive this warning about deprecated gulp-util.

```npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5```

**Comment by ModulesUnraveled** [comment]
I saw this too.

Since this is actually an `emulsify-gulp` issue, I've created an issue for it here: https://github.com/fourkitchens/emulsify-gulp/issues/79
