### ISSUE TITLE
Build not serve

### ISSUE THREAD

**Issue by BrizzleRocker** [fourkitchens/emulsify#273]
Is it possible to just build the theme and not serve? 

I am thinking for deployment to server where you would like to run tasks on a CI server and deploy compiled code. Can't find this in the documentation and it's not entirely clear from the setup. Does `gulp build` run everything `gulp theme` does without serving PL?

**Comment by evanmwillhite** [comment]
This is a great question and possibly a spot where we could do some refinement. I think we've always done gulp tasks individually depending on the build process we needed at a given time (not sure myself, the backend team lead usually sets this part up). But it seems to me that we could make sure `gulp build` builds what we would need for 90%+ situations. I ran it and the only thing I saw missing were the pattern lab related items (`pl:scss-to-yaml` and `gulp pl:full`). Want to test on your end, and see if adding those would give you what you need?

**Comment by evanmwillhite** [comment]
If so, let's move this over to emulsify gulp as an issue since our change would be needed [over there.](https://github.com/fourkitchens/emulsify-gulp/blob/develop/index.js#L158)

**Comment by evanmwillhite** [comment]
Decided to open that over there, so I'm gonna close this here. Thanks!
