### ISSUE TITLE
Yeoman Generator for creating components

### ISSUE THREAD

**Issue by grshane** [fourkitchens/emulsify#278]
I was tired of creating a directory and the subsequent files for every component, so I created a Yeoman generator to remove the repetitive tasks. 

Is this something that would be a good addition to Emulsify? If so, I see this living in a separate repo like Emulsify-Gulp and then included with npm/yarn. 

https://github.com/grshane/wvu-twig-component-generator

**Comment by evanmwillhite** [comment]
Nice! I am definitely open to this if you want to open a PR against Emulsify or Emulsify Gulp (you should get emails adding you as a collaborator to both).

**Comment by evanmwillhite** [comment]
Closing for now, but feel free to reopen if we need an issue.
