### ISSUE TITLE
The wiki needs a cleanup.

### ISSUE THREAD

**Issue by ModulesUnraveled** [fourkitchens/emulsify#281]
The Orientation page has this snippet:
`<div class="grid{% for modifier in grid_modifiers %} grid--{{ modifier }}{% endfor %}{% if grid_blockname %} {{ grid_blockname }}__grid{% endif %}">`

We replaced that with the BEM function a long time ago, so we should probably go over the wiki and update it where needed.

**Comment by evanmwillhite** [comment]
Working on this today.

**Comment by evanmwillhite** [comment]
OK, I believe I have wrapped this up now. I'm gonna close, but feel free to reopen if need be.
