### ISSUE TITLE
Where to elements.emulsify_xxx come from?

### ISSUE THREAD

**Issue by cristinallamas** [fourkitchens/emulsify#286]
https://github.com/fourkitchens/emulsify/blob/1cdf42b5066803841ee747132abe96f65b614e6b/templates/layout/region--header.html.twig#L20

I'm building a header myself, but I can't seem to understand this part of elements.emulsify_xxx from the tutorial 

https://www.fourkitchens.com/blog/development/emulsify-2-building-full-site-header-drupal/

Thanks

**Comment by thamas** [comment]
They write in the post:

> "You’ll notice that we are using the `elements` variable. _This variable is currently not listed_ in the Stable region template at the top, but is extremely useful in printing the blocks _that are currently in that region_." 

So as I mean, it is provided by Drupal, and it contains the Drupal blocks _that are in that region_.

**Comment by evanmwillhite** [comment]
Thanks @thamas!
