### ISSUE TITLE
npm errors after updating to Mojave 10.14

### ISSUE THREAD

**Issue by colinlord** [fourkitchens/emulsify#292]
Hi there,
I upgraded my Mac to Mojave and I'm now getting errors when I try npm start. This is my log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.2.0
3 info using node@v9.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle emulsify@1.0.0~prestart: emulsify@1.0.0
6 info lifecycle emulsify@1.0.0~start: emulsify@1.0.0
7 verbose lifecycle emulsify@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle emulsify@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/colinlord/Repos/cr/themes/custom/emulsify/node_modules/.bin:/Users/colinlord/.rvm/gems/ruby-2.1.5/bin:/Users/colinlord/.rvm/gems/ruby-2.1.5@global/bin:/Users/colinlord/.rvm/rubies/ruby-2.1.5/bin:/bin:/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/colinlord/.rvm/bin:/Users/colinlord/.rvm/bin
9 verbose lifecycle emulsify@1.0.0~start: CWD: /Users/colinlord/Repos/cr/themes/custom/emulsify
10 silly lifecycle emulsify@1.0.0~start: Args: [ '-c', 'gulp clean && gulp compile && gulp theme' ]
11 silly lifecycle emulsify@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle emulsify@1.0.0~start: Failed to exec start script
13 verbose stack Error: emulsify@1.0.0 start: `gulp clean && gulp compile && gulp theme`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid emulsify@1.0.0
15 verbose cwd /Users/colinlord/Repos/cr/themes/custom/emulsify
16 verbose Darwin 18.0.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v9.11.1
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error emulsify@1.0.0 start: `gulp clean && gulp compile && gulp theme`
22 error Exit status 1
23 error Failed at the emulsify@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by colinlord** [comment]
And here's what I have in my terminal:

 themes/custom/emulsify  npm start

> emulsify@1.0.0 start /Users/colinlord/Repos/cr/themes/custom/emulsify
> gulp clean && gulp compile && gulp theme

[15:27:36] Using gulpfile ~/Repos/cr/themes/custom/emulsify/gulpfile.js
[15:27:36] Task 'clean' is not in your gulpfile
[15:27:36] Please check the documentation for proper gulpfile formatting
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! emulsify@1.0.0 start: `gulp clean && gulp compile && gulp theme`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the emulsify@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/colinlord/.npm/_logs/2018-09-25T19_27_37_002Z-debug.log

**Comment by evanmwillhite** [comment]
@colinlord `gulp clean` was removed [awhile back](https://github.com/fourkitchens/emulsify-gulp/pull/86), so you can remove that from your package.json start script.
