### ISSUE TITLE
Twig_Error_Loader: Template "@molecules/pager/pager.twig" is not defined in "themes/custom/<themename>/templates/navigation/pager.html.twig" at line 32. in Twig_Loader_Chain->getCacheKey() (line 129 of /path/to/drupal/docroot/vendor/twig/twig/lib/Twig/Loader/Chain.php).

### ISSUE THREAD

**Issue by jfitzsimmons2** [fourkitchens/emulsify#302]
I'm having this issue after a fresh Drupal 8.6 install. I'm using Acquia DevDesktop to run the site. I have the 'components' module enabled but am still getting this error. PatternLab loads fine, but visiting the Drupal site produces a "The website encountered an unexpected error. Please try again later." message. Everything under /admin still loads fine.

**Comment by jfitzsimmons2** [comment]
Update: It seems to be an issue with DevDesktop. 

I just tried the same thing using DrupalVM and it works fine.

**Comment by christhorp** [comment]
I'm getting the same error - using Lando

Edit - my bad - I hadn't installed Components
