### ISSUE TITLE
Images problem

### ISSUE THREAD

**Issue by LadIQe** [fourkitchens/emulsify#310]
Hi, I want to ask about images.

First of all, I deleted all folders from components/_patterns, only 00-base left. Reason was, that I want to use uikit and there were problems with that.

Now, I want to create slider where you can slide between multiple images. It would be great, if it can dynamically change based on number of images in my folder, so if I have 5 images in folder, automatically my slider will change and use all of them, if 3 then 3 and so on. 

Now the hard part, I have no idea, how to point in my code to image folder. I called it promo, first I put it in components/images but I had no idea how to write path in twig. So I tried easier part to test it and I put it directly to folder, where is my code: molecules/slider

But it looks like it doesnt work, because pattern lab is not showing anything. Funny thing is, that Im able to create fully working code but with PHP, that twig thing is really strange language for me.

So is here someone who is willing to help dumb person (me) to solve my problem?

Thanks

edit: ok so now I can use slider with UIkit, but without twig language. I have this in slider.twig:

```
<div class="uk-container-expand uk-text-center uk-background-secondary">

	<div class="uk-position-relative uk-visible-toggle uk-light" uk-slider="center: true">

	    <ul class="uk-slider-items uk-grid">
	        <li class="uk-width-1-1">
	            <div class="uk-panel">
	                <img src="../../images/promo/ipad.jpg" alt="">
	            </div>
	        </li>
	        <li class="uk-width-1-1">
	            <div class="uk-panel">
	                <img src="../../images/promo/macbook-new.jpg" alt="">
	            </div>
	        </li>
	        <li class="uk-width-1-1">
	            <div class="uk-panel">
	                <img src="../../images/promo/iphone.jpg" alt="">
	            </div>
	        </li>
	    </ul>

	    <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
	    <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next"></a>

	</div>

</div>
```

As you can see, my test images are there, but with HTML help and its not dynamic. How can I write code in twig to dynamic change my slider? I know I have to use loop, for example for, foreach etc but how in twig?

**Comment by evanmwillhite** [comment]
@LadIQe Are you a member of [DrupalTwig Slack](https://drupaltwig.slack.com/)? That is a really active community built around helping folks with questions like this. I'm going to close this as there is no issue with Emulsify here per se, but people will still be able to find the issue and respond.
