### ISSUE TITLE
Documentation: What are the changes in version 3?

### ISSUE THREAD

**Issue by aangelinsf** [fourkitchens/emulsify#317]
We're evaluating using Emulsify 3 for a new project and would love to know on a high level what the changes are. Checked for a blog post but didn't see one. Cheers.

**Comment by evanmwillhite** [comment]
Sure! The major highlight is the addition of accessibility testing per component. When you're building a component, tests are run to ensure it is accessible using pa11y and you can configure the settings to your liking. We have a blog in the works about that piece specifically that should be releasing soon. 

Other highlights were fixes to the newer attach_library function (released before but had some bugs) that make it less prone to errors and more flexible for multiple files, external files, etc.). Other things are fairly minor, but here's the PRs if you want to peruse:

https://github.com/fourkitchens/emulsify/releases/tag/v3.0

Thanks!

**Comment by aangelinsf** [comment]
Thank you.
