### ISSUE TITLE
Drupal 8.6.10 twig error

### ISSUE THREAD

**Issue by Judder** [fourkitchens/emulsify#326]
Not sure if this is directly related to 8.6.10 but even creating a clean 'vanilla' theme using emulsify (dev branch) gives the following twig error, which I think is to do with the @variables not being defined for some reason

```
The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Twig_Error_Loader</em>: Template &quot;@organisms/_node.twig&quot; is not defined in &quot;themes/custom/test_theme/templates/content/node.html.twig&quot; at line 73. in <em class="placeholder">Twig_Loader_Chain-&gt;getCacheKey()</em> (line <em class="placeholder">129</em> of <em class="placeholder">vendor/twig/twig/lib/Twig/Loader/Chain.php</em>). <pre class="backtrace">Drupal\Core\Template\TwigEnvironment-&gt;getTemplateClass(&#039;@organisms/_node.twig&#039;) (Line: 424)
Twig_Environment-&gt;loadTemplate(&#039;@organisms/_node.twig&#039;, NULL) (Line: 362)
Twig_Template-&gt;loadTemplate(&#039;@organisms/_node.twig&#039;, &#039;themes/custom/test_theme/templates/content/node.html.twig&#039;, 73) (Line: 43)
__TwigTemplate_3888d39be29c4b8b69ac0dd3df0c55e3245910120f447d9ace603ed118e6b742-&gt;doDisplay(Array, Array) (Line: 428)
Twig_Template-&gt;displayWithErrorHandling(Array, Array) (Line: 399)
Twig_Template-&gt;display(Array) (Line: 407)
Twig_Template-&gt;render(Array) (Line: 64)
```

**Comment by Judder** [comment]
FYI I double checked that components was installed

[notice] Already enabled: components
[notice] Already enabled: unified_twig_ext

**Comment by evanmwillhite** [comment]
Do you happen to have two Emulsify (default or clone) themes enabled? Or any other theme enabled that uses the same component-libraries `organisms` namespace defined in THEME.info.yml?

**Comment by evanmwillhite** [comment]
Also, is [this](https://github.com/fourkitchens/emulsify/issues/302) related?

**Comment by Judder** [comment]
Many thanks for the reply and suggestions

I interestingly following your suggestions of a theme cache, so I went through and disabled every other theme we had installed, bar the default admin theme and the child emulsify theme, and after a `drush cache:rebuild` the theme roared into life again!

So strangely re-enabling them doesn't replicate the error - but guessing as you say it sounds like a potential namespace clash

Thanks again and much appreciated
