### ISSUE TITLE
dist/style.css not being attached

### ISSUE THREAD

**Issue by dchaffin** [fourkitchens/emulsify#327]
From my info.yml file ...

```
name: MyTheme
type: theme
description: Theme based on <a href="http://emulsify.info">Emulsify</a>.
base theme: stable
core: 8.x

# Libraries (These are loaded on every page. Use https://www.drupal.org/developing/api/8/assets#twig whenever possible.)
libraries:
  - mytheme/global
```

My libraries file ...

```
global:
  version: VERSION
  css:
    theme:
      dist/style.css: {}
```

But that css is not being attached to my site. 

I can edit /templates/layout/html.html.twig and see changes. 

I can edit part of /components/_patterns/05-pages/_html.twig and see changes, but I tried to change this line:

`<title>{{ head_title|safe_join(' ||| ') }}</title>`

... and the change didn't take (even after clearing cache). 

Am I missing something? Why is my .css file not being loaded? Is that head area getting overridden somewhere?

Thanks!

**Comment by dchaffin** [comment]
I replaced the title tag in the head with:

`<title>Am I editing the right thing?</title>`

... and that worked. I also removed the css-placeholder tag altogether and that went away, so I'm in the right place it seems, but I still can't figure out why my stylesheet is not attached.

**Comment by dchaffin** [comment]
Move along ... nothing to see here ... except a warning about naming a module and a theme the same thing. Even when you're working in two different installs and move your theme into another site and totally don't even think to realize for the better part of a day that you have this conflict.

**Comment by amazingrando** [comment]
@dchaffin I've been there too. _The pain is real._ ✋
