### ISSUE TITLE
Attribute "name" does not exist for Node "Twig\Node\CheckToStringNode".

### ISSUE THREAD

**Issue by jproctor** [fourkitchens/emulsify#332]
Drupal 8.6.11 and 8.6.12 update Twig, which caused a small pile of related problems: at least [d.o 3039408](https://www.drupal.org/project/drupal/issues/3039408), [d.o 3040000](https://www.drupal.org/project/radix/issues/3040000), [d.o 3040210](https://www.drupal.org/project/drupal/issues/3040210), and [d.o 3040269](https://www.drupal.org/project/drupal/issues/3040269).

The last of those, at least in my case, arose from having an older version of components/_twig-components/tags/pl_trans.tag.php, back when it was called just trans.tag.php. Renaming it fixed the issue so it doesn’t clobber Drupal core’s [TwigTransTokenParser](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Template%21TwigTransTokenParser.php/class/TwigTransTokenParser/8.6.x), but I notice that it still relies on `getAttribute('name')` on lines 118 and 120, and that attribute might not exist.

**Comment by evanmwillhite** [comment]
Thanks for letting us know. We already have [this PR](https://github.com/fourkitchens/emulsify/issues/294) in play, which will change the nature of that from something incorrectly doing Drupal-y things to something simple for PL, so I am going to close this one in favor of that one (particularly the new naming convention fixes the major error). But thanks again! Glad this is in the history, so others can find it too who might be on older versions.
