### ISSUE TITLE
Attributes question

### ISSUE THREAD

**Issue by dchaffin** [fourkitchens/emulsify#335]
In @atoms/_field.twig, I see:

`<div{{ attributes }}>`

But I can't tell that it's doing anything. I want to add a class to that. Is this the correct way?

```
{% include "@atoms/_field.twig" with {
  attributes: { '#class': 'field--image' }
} %}
```

Thanks!

**Comment by ctarres** [comment]
Hello.

I don't know if it's correct but you can use this:

`{% include "@atoms/_field.twig" with {
  attributes: create_attribute({'class': ['test', 'test--red']})
} %}
`

**Comment by dchaffin** [comment]
@ctarres - Thanks! That worked!
