### ISSUE TITLE
How to change browserSync port?

### ISSUE THREAD

**Issue by seanr** [fourkitchens/emulsify#343]
emulsify version (see [releases](https://github.com/fourkitchens/emulsify/releases)):

node version: 8.16.0

npm (or yarn) version: 6.4.1

**What you did:**
I'm attempting to change the browserSync port and copied the config to loca.gulp-config per the instructions with the following for the bS section:

```
    browserSync: {
      enabled: true,
      baseDir: './',
      startPath: 'pattern-lab/public/',
      // Uncomment below if using a specific local url
      domain: 'patterns.webolutionary.lndo.site',
      notify: false,
      openBrowserAtStart: false,
      reloadOnRestart: true,
      ui: false,
      port: 8000,
      // Clicks, Scrolls & Form inputs on any device will be mirrored to all others.
      // ghostMode: false to turn all off
      ghostMode: {
        clicks: true,
        forms: true,
        scroll: true,
        location: true
      }
    },
```

Note the addition of `port: 8000,`.

**What happened:**

After running npm start, I used to see this at the end:

```
[Browsersync] Access URLs:
 ----------------------------------------------------
    Local: http://localhost:3000/pattern-lab/public/
 External: http://172.23.0.2:3000/pattern-lab/public/
 ----------------------------------------------------
[Browsersync] Serving files from: ./
```

I now see this:

```
[Browsersync] Access URLs:
 -------------------------------------------------------
       Local: http://localhost:3000/pattern-lab/public/
    External: http://172.20.0.3:3000/pattern-lab/public/
 -------------------------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 -------------------------------------------------------
```

It's now ignoring the `ui: false` setting (which I had left unchanged) and is still using the wrong port. Additionally, no longer says "serving files..."

**Problem description:**

I am attempting to run this from within a Lando service (https://docs.devwithlando.io/) and want to be able to change the port to one that is easier to configure Lando with (I've been having trouble with Docker when trying to change Lando's proxy).

[local.gulp-config.js.zip](https://github.com/fourkitchens/emulsify/files/3298461/local.gulp-config.js.zip)

**Comment by seanr** [comment]
Ugh, looks like this in `./node_modules/emulsify-gulp/index.js` precludes the use of a custom port for browserSync?

```
  // Find open port using portscanner.
  let openPort = '';
  portscanner.findAPortNotInUse(3000, 3010, '127.0.0.1', (error, port) => {
    openPort = port;
  });
```

Shouldn't that be configurable? It is an available option in browserSync, so ideally, Emulsify would respect that. In the meantime, I'm trying to get help from the Lando folks for the other end of this problem. I'm desperately trying to avoid what I did on my last project, which required a whole separate service just for that one thing (and way too much scripting).

**Comment by seanr** [comment]
This apparently needs to move to emulsify-gulp, but I don't see a way to do so (d.o's projects module has GitHub beat here? LOL).

**Comment by evanmwillhite** [comment]
Hmm.. we may have to change this. Our approach was to use that script above to find the first available open port (allows more than 1 instance of Emulsify to run at once), but it sounds like this might be a case where a specific port is required. In that case, I could see [this line](https://github.com/fourkitchens/emulsify-gulp/blob/develop/index.js#L119) being something like:

`port: config.browserSync.port || openPort,`

I haven't tested that, but I wonder if it will use your port from your config and then fall back to our plan. If so, that might be worth a PR.

**Comment by seanr** [comment]
@evanmwillhite I tried that (which seems like it should work), but with the local.gulp-config.js, it seems to be just resetting everything to the browserSync defaults rather than what's in either index.js or my local.gulp-config.js (see the two console snippets from above). Your snippet probably would work but for this other issue.

**Comment by evanmwillhite** [comment]
Oh, you're using `domain`, which has a different method of creating it. Not sure off the top of my head, but it seems likely the fix would be somewhere in [here](https://github.com/fourkitchens/emulsify-gulp/blob/develop/index.js#L100-L107). Local config will just override the config values (config.browserSync.VALUE), but it will still use this gulp serve task.

**Comment by seanr** [comment]
I ended up getting this to work a different way, so I think this can be closed if you'd like (though I can still create a PR for that fix above), but I'm happy to provide documentation for my specific use case. The problem, more than anything, seemed to be on the Lando side of things (they'll get a doc update themselves).
