### ISSUE TITLE
Readme installation typo error.

### ISSUE THREAD

**Issue by code-r-man** [fourkitchens/emulsify#354]
emulsify version (see [releases](https://github.com/fourkitchens/emulsify/releases)): 3.1

node version: 10.17.0

npm (or yarn) version: 6.11.3

**What you did:** Tried to activate `emulsify` via `drush`

**What happened:** Got an error: `The drush command 'then...' could not be found`

**Reproduction repository (if necessary):**

**Problem description:**

**Suggested solution:** Please change the word `then` to `en` in the installation instructions as this is a typo.

**Comment by ModulesUnraveled** [comment]
Hey, @code-r-man thanks for reporting!

This is actually the correct command for the latest Drush version (drush 9) Drush 8 and earlier use the `en` command.

https://drushcommands.com/drush-9x/theme/theme:enable/

If you'd like to submit a PR to spell out the different commands needed, I'd review that, but we're mostly focusing on the new Emulsify Design System (which will supersede this at release) so we're not spending a lot of time on docs etc. for this version of Emulsify.
