### ISSUE TITLE
font-size mixin fix

### ISSUE THREAD

**Issue by evanmwillhite** [fourkitchens/emulsify#55]
Currently Emulsify has a font size mixin to use REMs with a PX fallback. Let's replace this with a PostCSS task that will automagically give a PX fallback.

Implement: https://www.npmjs.com/package/gulp-pixrem

**Comment by evanmwillhite** [comment]
Are we ok just using rems and adding a fallback as-needed on this considering current support is solid?

**Comment by ModulesUnraveled** [comment]
We removed the font-size mixin. So, I'm closing this issue
