### ISSUE TITLE
Using Foundation or Bootstrap as starter

### ISSUE THREAD

**Issue by fabean** [fourkitchens/emulsify#58]
Is there a way to include the Foundation or Bootstrap Sass to use that as a base when building my theme with Emulsify? This would allow us to keep using a tool we know while incorporating this project.

We tried just putting all the Foundation .scss in `components/_patterns/*` but it's throwing errors.

Hoping you have good advice on the best path to take.

**Comment by ylynfatt** [comment]
@fabean shouldn't the scss files be put in `components/css/scss` folder and then you import them in the `components/css/style.scss` file?

**Comment by evanmwillhite** [comment]
`components/css/*` are Pattern Lab related stylesheets, so I wouldn't put them there myself organizationally speaking. I would either put them in `components/_patterns/00-base` or a separate vendor directory but that would require more work if sass needs to be compiled. @fabean can you just reference a minified CSS file for the foundation/bootstrap CSS? If so, you can add the reference to that file in `components/_meta/_00-head.twig`. This is the `<head>` HTML of the Pattern Lab installation. This would keep you from having to compile the Foundation/Bootstrap Sass in your build process too.

**Comment by evanmwillhite** [comment]
@fabean did this help with your question?

**Comment by evanmwillhite** [comment]
Closing this out for now.
