### ISSUE TITLE
Twig_Error_Loader: Template "@molecules/pager/pager.twig" is not defined 

### ISSUE THREAD

**Issue by sinyayadynya** [fourkitchens/emulsify#70]
Hi,

On a new install, I can run npm start and check pattern lab, but on the site itself, I'm having:
The website encountered an unexpected error. Please try again later.

with this log message: 
Twig_Error_Loader: Template "@molecules/pager/pager.twig" is not defined (Drupal\Core\Template\Loader\ThemeRegistryLoader: Unable to find template "@molecules/pager/pager.twig" in the Drupal theme registry.) in "themes/contrib/emulsify/templates/navigation/pager.html.twig" at line 32. in Twig_Loader_Chain->getCacheKey() (line 129 of mysite/vendor/twig/twig/lib/Twig/Loader/Chain.php).

Any idea what is wrong? Thanks for help

**Comment by evanmwillhite** [comment]
It sounds like you may have not enabled the [Components](https://www.drupal.org/project/components) Drupal module. This is a requirement when using Emulsify with Drupal, as the module enables custom template directories (see the "component-libraries:" section in emulsify.info.yml).

**Comment by evanmwillhite** [comment]
@sinyayadynya did this solve your problem? Just going through to close out issues if it did.

**Comment by sinyayadynya** [comment]
Yes, thanks @evanmwillhite!
It is working now, but I did not noticed that it was because I had later enabled the Components Drupal module.

**Comment by jfitzsimmons2** [comment]
I'm having this same issue after a fresh Drupal 8.6 install. I have the 'components' module enabled but am still getting this error. PatternLab loads fine, but visiting the Drupal site produces a "The website encountered an unexpected error. Please try again later." message.

Screenshot of dblog below
![screen shot 2018-11-14 at 11 36 26 am](https://user-images.githubusercontent.com/1531748/48497342-f2262e80-e801-11e8-8932-b3a82bef8ac1.png)
