### ISSUE TITLE
Is it recommended to create a subtheme?

### ISSUE THREAD

**Issue by sinyayadynya** [fourkitchens/emulsify#74]
Hi, 
As I'm just starting to explore emulsify, I'm wondering if it is recommended/needed to create a subtheme, or if I can just modify emulsify?
And if a subtheme is needed, could you please give some hint about how to create it?
Thanks!

**Comment by ModulesUnraveled** [comment]
Right now, our current recommendation is to clone Emulsify from Github, and place it in your `/themes/custom` directory. From that point on, it's a custom theme for that project.

The idea being that Emulsify is boiler plate code that we found ourselves writing from scratch for each site, and wanted to shortcut the process.

We're actively exploring how to do sub-theming, or whether that's needed, or how we can provide something that is "composer update-able". But for now, just clone it into your project, and customize it as you wish.
