### ISSUE TITLE
Explore moving to global data versus local yml files

### ISSUE THREAD

**Issue by evanmwillhite** [fourkitchens/emulsify#76]
We could still use local files as necessary, but it sounds like this approach may reduce our data like our approach to handling atoms has reduced our markup.

Basically, we can use the _data directory to house global data files (apparently supports multiple files), and we can move to a different approach in how we set up Twig files.This requires the following:

1. Change _data files to yml files and separate out data as we see fit for readability
2. Move to the approach of having 2 kinds of components ([Evan Lovely's approach](http://www.evanlovely.com/blog/2017/05/twig-pattern-lab-better-variant-pseudo-patterns/)) -presentational and container components. Basically, one provides vars/markup and the presentational ones are the ones that are given explicit data and then reused within larger components. This allows data to pass through all and removes the headache of copying data (which can always be done as needed by including the container component instead of the presentational one).

**Comment by EvanLovely** [comment]
Heads up: there's a weird bug where all yaml files in `_data/` need to use `.yaml` and can't use `.yml` - even though the Pseudo Patterns data can be `.yaml` or `.yml`. I've got [a PR into core](https://github.com/pattern-lab/patternlab-php-core/pull/98) that's been sitting since Oct 2016... perfect example of stuff that we should merge into our forks. And yes, you can have multiple files of `.json` or `.yaml` in `_data/` and they all merge. Filenames are ignored.

**Comment by evanmwillhite** [comment]
@EvanLovely you're the man! Is there any way we can help step in to review/accept those PRs? It seems like the PL team could use some help.

**Comment by EvanLovely** [comment]
We'd just need to open that same PR up against our fork. Also would need to point Emulsify at our forks; I'll be doing that with Pattern Lab Starter soon.

**Comment by evanmwillhite** [comment]
We decided to keep our approach as-is, because (more or less) the isolation of data involved in the component yml approach is more important than the speed of prototyping available via global data files and presentational components. May change later, but I'll close this for now.
