### ISSUE TITLE
No .logo class anymore?

### ISSUE THREAD

**Issue by sinyayadynya** [fourkitchens/emulsify#82]
Hi,
Since the last update it seems that the .logo class is not applied by default and I don't see how to put it back. Any help welcome.

**Comment by ModulesUnraveled** [comment]
Hi @sinyayadynya, we refactored the logo component to utilize the image component, and optionally the link component. You can find the latest iteration here: https://github.com/fourkitchens/emulsify/blob/master/components/_patterns/01-atoms/04-images/01-logo/logo.twig

TL;DR: Set `logo_image_base_class: "logo"` and you'll have it back!

**Comment by sinyayadynya** [comment]
@ModulesUnraveled thanks for pointing me out that change.

However, I'm still a bit lost within Emulsify and specially this logo story.

What I have done, without much success, is to

- add a logo.svg file at the root
- create a 'templates/block/block--system-branding-block.html.twig' file with the following content: 

{% include "@molecules/_block.twig" 
	with {
		logo_image_base_class: "logo"
	}
%}

For sure, I'm missing something. Could you please give me more information?

Special thanks.

**Comment by ModulesUnraveled** [comment]
Two things:
1. Make sure the "_block.twig" file is pulling in the logo.twig file.

2. Take a look at the logo.twig file, and see where it's expecting the file to live. I think it's supposed to be in one of the "Images" directories. Alternatively you can update the logo.twig file to point to the theme root.

**Comment by sinyayadynya** [comment]
Thanks, I'm looking toward that direction. But just one more question: is it possible that way to use a svg file instead of png?

**Comment by ModulesUnraveled** [comment]
Yes! Just update the logo.twig file to point to a "logo.svg" file. You have complete control! :)

**Comment by sinyayadynya** [comment]
Good! Here is what I ended with in my 'templates/block/block--system-branding-block.html.twig' file: 
`{% include "@atoms/04-images/00-image/image.twig"
	with {
		"img_src": logo_src|default('/themes/custom/emulsify/images/logo.svg'),
		"logo_image_base_class": "logo",
		"img_alt": logo_alt|default('Logo'),
	}
%}`

Thanks for your support.

Only I'm still trying to figure out how to update the logo inside pattern lab. Should I modify the original 'patterns/01-atoms-04-images-01-logo-logo/01-atoms-04-images-01-logo-logo.twig' or is there an other way?

**Comment by ModulesUnraveled** [comment]
Here's an example of what I'm doing on an existing site:

The logo is at `/themes/custom/emulsify/components/images/logo.svg`

My logo.twig file looks like this:
```
{% set logo_blockname_var = logo_blockname|default('logo') %}
{% embed "@atoms/01-links/link/link.twig"
  with {
    "link_blockname": logo_blockname_var,
    "link_base_class": logo_link_base_class,
    "link_url": logo_url|default('/'),
  }
%}
  {% block link_content %}
    {% include "@atoms/04-images/00-image/image.twig"
      with {
        "image_base_class": logo_image_base_class,
        "image_blockname": logo_blockname_var,
        "img_src": logo_src|default('../../images/logo.svg'),
        "img_alt": logo_alt|default('Logo'),
      }
    %}
  {% endblock %}
{% endembed %}
```

Then, you could simply put this in your `branding-block.html.twig`
```
{% include "@atoms/path/to/your/logo.twig" %}
```

**Comment by sinyayadynya** [comment]
Thank you so much @ModulesUnraveled, this help me a lot to understand the full logic. 

I can now close the issue as you answered beyond all expectations!

**Comment by ModulesUnraveled** [comment]
Awesome! So happy to have helped!

**Comment by sinyayadynya** [comment]
@ModulesUnraveled: Using the last version of Emulsify, I'm getting the following error, after copying my logo files:

`Uncaught PHP Exception Twig_Error_Loader: "Template "@atoms/04-images/01-logo/logo.twig" is not defined (Drupal\Core\Template\Loader\ThemeRegistryLoader: Unable to find template "@atoms/04-images/01-logo/logo.twig" in the Drupal theme registry.) in "themes/custom/corp/templates/block/block--system-branding-block.html.twig" at line 28." at /Users/sahaj/Sites/mounteccorp/vendor/twig/twig/lib/Twig/Loader/Chain.php line 129`

I guess that the logic have changed, but I don't find how to adapt that customization. Any help welcome.

**Comment by ModulesUnraveled** [comment]
@sinyayadynya First, I want to make sure that you're starting from scratch with Emulsify 2.x. There is no upgrade path from 1.x.

Assuming that's correct, and you're just trying to get setup on 2.x (so that updates won't break anything going forward) we actually got rid of the logo component back in July since it was really just a variation of the image component.

You are, of course, free to create components like the old logo.twig, but we decided since it didn't provide any additional value over the image.twig component, we'd just consolidate in Emulsify Core.

Here's the relevant PR: https://github.com/fourkitchens/emulsify/pull/96/files

So, I'd recommend one of two things:
1. In your template include the image.twig component and update the variables accordingly e.g.: `logo_link_base_class` will become `image_link_base_class` (Recommended)
2. Recreate the logo.twig file for your project

**Comment by sinyayadynya** [comment]
I mean, I can live without my old "@atoms/04-images/01-logo/logo.twig" template, my only issue is that the logo have no link to the frontpage and that I cannot find why and how to add it.

**Comment by ModulesUnraveled** [comment]
That's all available in the image.twig file: https://github.com/fourkitchens/emulsify/blob/master/components/_patterns/01-atoms/04-images/00-image/image.twig

On line 21 you'll find: `"link_url": img_url,`

So, in your site-branding block template (or wherever you're adding the logo) you'd say
```
{% include "@atoms/04-images/00-image/image.twig" with {
  "img_url": "/",
  "image_base_class": "logo",
  "image_blockname": "logo",
  "img_src": default('../../images/logo.svg'),
  "img_alt": default('Logo'),
  ...
```

Or something like that

**Comment by sinyayadynya** [comment]
Sorry, our post crossed. Thanks for pointing me that new components/_patterns/01-atoms/04-images/00-image/image~logo.yml file.

And yes,  I'm now on the last version (Emulsify 2.x).

So, now I'm using only in my block template (block--corp-branding.html.twig) the following: 

```
{% include "@atoms/04-images/00-image/image.twig" 
  with {
    "img_url": "/",
    "image_base_class": "logo",
    "image_blockname": "logo",
    "img_src": default('../../images/logo.png'),
    "img_alt": default('Logo'),
  }
%}
```

But then I'm getting this error: 

`Uncaught PHP Exception Twig_Error_Syntax: "Unknown "default" function." at /Users/sahaj/Sites/mounteccorp/web/themes/custom/corp/templates/block/block--corp-branding.html.twig line 34 `

Line 34 being **"img_src": default('../../images/logo.png'),**

I'm ashamed, but what else am I missing?

**Comment by ModulesUnraveled** [comment]
Whoops! my bad.
Those should just be:
```
    "img_src": "../../images/logo.png",
    "img_alt": "Logo",
```

No need for the `default` stuff since you're not setting a new variable that can be replaced. In this case you're just setting a variable, so you can just set it.

**Comment by sinyayadynya** [comment]
Ok @ModulesUnraveled, thanks for your fast and helpful replies. 

As I came back to my project after few months of inactivity, I wanted to update to the last version of Emulsify. Now should be ok.

Don't know also how much Emulsify will evolve from now, but will try to follow it closely.
