### ISSUE TITLE
Sidebar markup

### ISSUE THREAD

**Issue by sinyayadynya** [fourkitchens/emulsify#85]
In '`components/_pattern/05-page/_page.twig`', the sidebar have a '`main-sidebar`' class and the content a '`main-content(&--with-sidebar)`' class, 

while in '`components/_pattern/05-page/_page.scss`' the class in use are '`.layout-sidebar`' and '`.layout-content(&--no-sidebar)`'.

Is it a mistake or am I missing something?

**Comment by evanmwillhite** [comment]
Yea, that's a mistake - good catch. I've addressed in the PR above and also cleaned up that file a bit in general. Want to review?

**Comment by sinyayadynya** [comment]
Sure @evanmwillhite, that file looks ok now for me. I have tested the code without issue. Big thanks!

**Comment by evanmwillhite** [comment]
Thank you!
