### ISSUE TITLE
@atoms/05-forms/checkbox/_checkboxes.twig" is not defined 

### ISSUE THREAD

**Issue by sinyayadynya** [fourkitchens/emulsify#88]
I'm getting the following error using Mailchimp form with checkboxes:

`Uncaught PHP Exception Twig_Error_Loader: "Template "@atoms/05-forms/checkbox/_checkboxes.twig" is not defined (Drupal\\Core\\Template\\Loader\\ThemeRegistryLoader: Unable to find template "@atoms/05-forms/checkbox/_checkboxes.twig" in the Drupal theme registry.) in "themes/custom/emulsify/templates/form/checkboxes.html.twig" at line 15." at /Users/sahaj/Sites/mounteccorp/vendor/twig/twig/lib/Twig/Loader/Chain.php line 129, referer: http://mysite.com/admin/config/services/mailchimp/signup`

And actually, I'm not sure if it is enough to simply correct the line 15 of themes/custom/emulsify/templates/form/checkboxes.html.twig from
`{% include "@atoms/05-forms/checkbox/_checkboxes.twig" %}`
to 
`{% include "@atoms/05-forms/checkbox/checkbox.twig" %}`
or if this should be addressed another way.

Also, if I did not met any other issue yet, it seems that there is more un-matching code within themes/custom/emulsify/templates/form/

Did anybody else notice such issue?

Thanks for help.

**Comment by sinyayadynya** [comment]
Replacing  the line 15 of themes/custom/emulsify/templates/form/checkboxes.html.twig from
{% include "@atoms/05-forms/checkbox/_checkboxes.twig" %}
to
{% include "@atoms/05-forms/checkbox/checkbox.twig" %}

avoid to display the error message, but it does not fix totally the issue, in the way that the checkboxes are not displayed.

**Comment by evanmwillhite** [comment]
This is a great question, and one for which I don't have the best answer. :) There are a couple of Drupal items that we have yet to incorporate into full component-based theming, which are the menu system and forms. So, `components/_patterns/01-atoms/05-forms/_checkboxes.twig` is actually authoritative. That is what is getting leveraged in Drupal (as you can see in `templates/form/checkboxes.html.twig`). The component Twig files in `components/_patterns/01-atoms/05-forms` are just placeholder markup to style. In other words, it's up to you (and us) to make sure the classes stay the same in the authoritative files as the component files.

And hear me say - this above is not ideal and is an example of why we wanted to move to component-based theming (having two separate files is fragile). We would _like_ to try and separate out menu items and form items into separate components and make sure everything works great with their respective Drupal APIs, but it's a larger task that hasn't happened yet.

**Comment by ccjjmartin** [comment]
@sinyayadynya Can you elaborate as to how you were able to add the checkbox to the MailChimp signup form?  I don't see checkbox as an available field within the MailChimp interface?

![screen shot 2017-06-20 at 10 47 45 pm](https://user-images.githubusercontent.com/12279982/27366277-ad494b74-560a-11e7-9fd1-9261d7f38d58.png)

I am assuming that you installed the MailChimp module and its counterpart MailChimp Signup.

**Comment by sinyayadynya** [comment]
@ccjjmartin this is for instance when there is several lists to choose from on the form page.

**Comment by amazingrando** [comment]
Reading above it looks like the original issue's solution is that the feature is not yet implemented. (We're working towards it.) I'm going to close this issue. Reopen if I'm in error.
