### ISSUE TITLE
Template not defined

### ISSUE THREAD

**Issue by nmacd85** [fourkitchens/emulsify#91]
It seems no matter what I try to add, unless its already in the theme, Drupal cannot find my templates and I get the error 

`15-Jun-2017 11:32:17 America/Halifax] Uncaught PHP Exception Twig_Error_Loader: "Template "@organisms/slider/slider.twig" is not defined (Drupal\Core\Template\Loader\ThemeRegistryLoader: Unable to find template "@organisms/slider/slider.twig" in the Drupal theme registry.) in "themes/custom/flolab/templates/content/node--technology.html.twig" at line 1." at /Applications/MAMP/htdocs/drupal-patterns/vendor/twig/twig/lib/Twig/Loader/Chain.php line 115
 `
Within my node drupal template I have the following
`{% include "@organisms/slider/slider.twig" %}`

And within that exact directory I have the slider.twig file and plain text just to try to get it loading. I have also made sure to clear cache and even run `npm start` again.

Is the theme not ready for adding our own custom components or am I missing a step? 

Thanks!

**Comment by evanmwillhite** [comment]
Have you enabled the components module by chance? It is a [requirement](https://github.com/fourkitchens/emulsify#drupal-specific-installation) for usage in Drupal.

**Comment by nmacd85** [comment]
Sure have.

**Comment by evanmwillhite** [comment]
Hmm... good question. Did you happen to tweak the emulsify.info.yml file particularly [these lines](https://github.com/fourkitchens/emulsify/blob/master/emulsify.info.yml#L45-L63)? If not, can you share your codebase by chance (or just the theme)?

**Comment by nmacd85** [comment]
Just pushed it up at https://github.com/nmacd85/flolab

I didn't change much of anything except renaming, so emulsify is now flolab. Everything installed fine, and runs fine except when I add the custom component.

**Comment by evanmwillhite** [comment]
Yea, everything looks good to me at a glance. I wonder if it's because the theme has been renamed. Did you rename everything before you enabled it? Have you tried disabling and reenabling? Sorry for the troubleshooting back-and-forth - this is a unique problem!

**Comment by nmacd85** [comment]
Yeah it seems okay with the original theme so it could be I renamed something that should have been renamed. I have switched back and forth between themes though and still an issue with mine. 

Might need to duplicate again but keep track of the renaming.

**Comment by evanmwillhite** [comment]
If the original emulsify theme is still present, I wonder if [Drupal's packaging script](https://github.com/nmacd85/flolab/blob/master/flolab.info.yml#L65) is causing confusion between the two? Totally guessing at this point, but it's odd that it would recognize some templates and not others - reminds me of previous issues I've run into when renaming themes.

Sorry again - let me know if you figure out it's something that we can fix and/or document.

**Comment by nmacd85** [comment]
Will do, thanks for your help/time! :)

**Comment by evanmwillhite** [comment]
No problem!

**Comment by nmacd85** [comment]
Just as an update, originally I do think I renamed something incorrectly but it was probably more due to not restarting npm start after adding new files. It seemed to be confused when I did that
