### ISSUE TITLE
Stylelint Update - Unhandled promise rejection, no configuration provided error

### ISSUE THREAD

**Issue by evanmwillhite** [fourkitchens/emulsify#94]
We just updated Emulsify to support Stylelint usage. If you run an install against the latest code, everything should run as normal (with new stylelinting goodness). However, if you are using an older version of Emulsify and running it against some kind of automated deployment tool that might get the latest from [emulsify-gulp](https://github.com/fourkitchens/emulsify-gulp) but not the main Emulsify repo, then you may need to add the [.stylelintrc](https://github.com/fourkitchens/emulsify/blob/master/.stylelintrc) file to the root of your Emulsify repo. 

Hopefully this helps! If you have any questions or are having issues, feel free to respond to this thread.

**Comment by jerseycheese** [comment]
Whew, thank you so much for this info! Was hitting this and was clueless as to what was going on.

**Comment by evanmwillhite** [comment]
Closing this as it is fairly old and documented now
